spring:
  profiles:
    active:
    - dev
---
server:
  port: 81
  context-path: /

spring:
  profiles: dev
  application:
    name: microservice-student

# ribbon 相关配置
eureka:
  client:
    #register-with-eureka: false  由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以设置为false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# 单机 需要指定服务提供者的IP+端口
provider_host: http://localhost:1004

---
server:
  port: 82
  context-path: /

spring:
  profiles: test
  application:
    name: microservice-student

# ribbon 相关配置
eureka:
  client:
    #register-with-eureka: false  由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以设置为false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka2001.etjava.com:2001/eureka/,
                    http://eureka2002.etjava.com:2002/eureka/,
                    http://eureka2003.etjava.com:2003/eureka/


# 单机 需要指定服务提供者的IP+端口
provider_host: http://localhost:1004

